import { Risk } from "./types";

// ============================================================================
// MOCK DATA (ICH Q9 compliant)
// ============================================================================
export const MOCK_RISKS: Risk[] = [
  {
    id: "1",
    riskId: "RSK-2026-001",
    title: "Cross-Contamination Risk - Multi-Product Facility",
    description: "Risk of cross-contamination between beta-lactam and non-beta-lactam products in shared facility",
    category: "Quality",
    level: "High",
    status: "Mitigation In Progress",
    assessmentMethod: "FMEA",
    probability: 3,
    severity: 5,
    detectability: 3,
    rpn: 45,
    identifiedBy: "QA Risk Team",
    identifiedDate: "2026-01-10",
    department: "Production",
    mitigationPlan: "Implement dedicated air handling, cleaning validation, and campaign manufacturing",
    reviewDate: "2026-04-10",
    assignedTo: "Production Director",
    reviewer: "QA Director",
    createdAt: "2026-01-10T09:00:00",
    updatedAt: "2026-01-25T15:00:00",
  },
  {
    id: "2",
    riskId: "RSK-2026-002",
    title: "Data Integrity Risk - Legacy LIMS System",
    description: "Audit trail gaps in laboratory data management system version 4.2",
    category: "Data Integrity",
    level: "Very High",
    status: "Escalated",
    assessmentMethod: "Risk Matrix",
    probability: 4,
    severity: 5,
    detectability: 4,
    rpn: 80,
    identifiedBy: "IT Compliance Team",
    identifiedDate: "2026-01-05",
    department: "IT / QC Lab",
    mitigationPlan: "Upgrade LIMS to version 6.0 with full 21 CFR Part 11 compliance",
    reviewDate: "2026-03-05",
    assignedTo: "IT Director",
    reviewer: "QA Director",
    approver: "Site Director",
    createdAt: "2026-01-05T10:30:00",
    updatedAt: "2026-01-24T11:00:00",
  },
  {
    id: "3",
    riskId: "RSK-2026-003",
    title: "Supply Chain Disruption - Single Source API",
    description: "Active pharmaceutical ingredient sourced from single supplier with no qualified alternative",
    category: "Supply Chain",
    level: "High",
    status: "Mitigation Planned",
    assessmentMethod: "PHA",
    probability: 3,
    severity: 4,
    detectability: 2,
    rpn: 24,
    identifiedBy: "Supply Chain Manager",
    identifiedDate: "2026-01-15",
    department: "Procurement",
    mitigationPlan: "Qualify second API supplier within 6 months",
    reviewDate: "2026-07-15",
    assignedTo: "Procurement Team",
    createdAt: "2026-01-15T08:00:00",
    updatedAt: "2026-01-20T14:30:00",
  },
  {
    id: "4",
    riskId: "RSK-2025-045",
    title: "Environmental Monitoring Gaps in Isolator",
    description: "Particle count sampling frequency insufficient per EU-GMP Annex 1",
    category: "Environmental",
    level: "Medium",
    status: "Mitigated",
    assessmentMethod: "HACCP",
    probability: 2,
    severity: 4,
    detectability: 2,
    rpn: 16,
    identifiedBy: "Validation Team",
    identifiedDate: "2025-11-20",
    department: "Sterile Manufacturing",
    mitigationPlan: "Increased sampling to continuous monitoring during Grade A operations",
    residualRisk: "Low",
    reviewDate: "2026-05-20",
    assignedTo: "EM Coordinator",
    reviewer: "QA Manager",
    approver: "QA Director",
    createdAt: "2025-11-20T09:00:00",
    updatedAt: "2026-01-15T10:00:00",
  },
  {
    id: "5",
    riskId: "RSK-2026-004",
    title: "Regulatory Non-Compliance Risk - GMP Certificate Expiry",
    description: "EU-GMP certificate for Site B expiring in 90 days without renewal application",
    category: "Regulatory",
    level: "Very High",
    status: "Under Assessment",
    assessmentMethod: "Risk Matrix",
    probability: 4,
    severity: 5,
    detectability: 1,
    rpn: 20,
    identifiedBy: "Regulatory Affairs",
    identifiedDate: "2026-01-25",
    department: "Regulatory Affairs",
    reviewDate: "2026-02-25",
    assignedTo: "RA Director",
    createdAt: "2026-01-25T11:00:00",
    updatedAt: "2026-01-25T11:00:00",
  },
];
