import { Product } from "./types";

// ============================================================================
// MOCK DATA
// ============================================================================
export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    productId: "PRD-001",
    name: "Amoxicillin Capsules 500mg",
    description: "Broad-spectrum penicillin antibiotic capsules",
    type: "Finished Product",
    status: "Commercially Available",
    dosageForm: "Capsule",
    strength: "500mg",
    activeIngredient: "Amoxicillin Trihydrate",
    manufacturer: "PharmaCorp EU",
    maNumber: "EU/1/2020/001",
    shelfLife: "36 months",
    storageConditions: "Below 25°C, protect from moisture",
    markets: ["EU", "UK", "Switzerland"],
    batchSize: "500,000 capsules",
    responsiblePerson: "Dr. Elena Vasquez",
    lastReviewDate: "2025-06-15",
    nextReviewDate: "2026-06-15",
    createdAt: "2020-03-15T10:00:00",
    updatedAt: "2025-12-01T09:00:00",
  },
  {
    id: "2",
    productId: "PRD-002",
    name: "Metformin HCl Tablets 850mg",
    description: "Anti-diabetic oral solid dosage form",
    type: "Finished Product",
    status: "Commercially Available",
    dosageForm: "Tablet",
    strength: "850mg",
    activeIngredient: "Metformin Hydrochloride",
    manufacturer: "PharmaCorp EU",
    maNumber: "EU/1/2019/045",
    shelfLife: "24 months",
    storageConditions: "Below 30°C",
    markets: ["EU", "UK"],
    batchSize: "1,000,000 tablets",
    responsiblePerson: "Dr. Franz Keller",
    lastReviewDate: "2025-04-20",
    nextReviewDate: "2026-04-20",
    createdAt: "2019-09-10T10:00:00",
    updatedAt: "2025-11-15T14:30:00",
  },
  {
    id: "3",
    productId: "PRD-003",
    name: "Ceftriaxone for Injection 1g",
    description: "Third-generation cephalosporin antibiotic for IV/IM administration",
    type: "Finished Product",
    status: "Under Variation",
    dosageForm: "Injection",
    strength: "1g",
    activeIngredient: "Ceftriaxone Sodium",
    manufacturer: "PharmaCorp EU",
    maNumber: "EU/1/2021/012",
    shelfLife: "24 months",
    storageConditions: "Below 25°C, protect from light",
    markets: ["EU", "UK", "Middle East"],
    batchSize: "200,000 vials",
    responsiblePerson: "Dr. Anna Schmidt",
    lastReviewDate: "2025-08-10",
    nextReviewDate: "2026-08-10",
    createdAt: "2021-06-20T10:00:00",
    updatedAt: "2026-01-15T09:00:00",
  },
  {
    id: "4",
    productId: "PRD-004",
    name: "Ibuprofen Oral Suspension 100mg/5mL",
    description: "Non-steroidal anti-inflammatory oral suspension for pediatric use",
    type: "Finished Product",
    status: "Development",
    dosageForm: "Suspension",
    strength: "100mg/5mL",
    activeIngredient: "Ibuprofen",
    manufacturer: "PharmaCorp EU",
    shelfLife: "18 months",
    storageConditions: "Below 25°C, do not freeze",
    markets: ["EU"],
    responsiblePerson: "Dr. Sarah Chen",
    createdAt: "2025-09-01T10:00:00",
    updatedAt: "2026-01-20T11:00:00",
  },
  {
    id: "5",
    productId: "PRD-005",
    name: "Omeprazole Delayed-Release Capsules 20mg",
    description: "Proton pump inhibitor for gastric acid reduction",
    type: "Finished Product",
    status: "Registered",
    dosageForm: "Capsule",
    strength: "20mg",
    activeIngredient: "Omeprazole",
    manufacturer: "PharmaCorp EU",
    maNumber: "EU/1/2025/098",
    shelfLife: "24 months",
    storageConditions: "Below 25°C, protect from moisture",
    markets: ["EU"],
    batchSize: "750,000 capsules",
    responsiblePerson: "Dr. Hans Mueller",
    createdAt: "2025-01-15T10:00:00",
    updatedAt: "2026-01-10T09:00:00",
  },
];
