import { CAPA } from "./types";

// Mock Data
export const MOCK_CAPAS: CAPA[] = [
  {
    id: "1",
    capaId: "CAPA-2026-001",
    title: "Improve Temperature Monitoring System",
    description:
      "Implement automated temperature monitoring for all cold storage areas",
    type: "Preventive",
    source: "Deviation",
    status: "Implementation",
    initiatedBy: "Dr. Sarah Johnson",
    initiatedDate: "2026-01-25",
    department: "Quality Assurance",
    relatedDeviationId: "DEV-2026-001",
    problemStatement: "Temperature excursions due to manual monitoring delays",
    rootCause: "Lack of real-time temperature monitoring and alerts",
    correctiveAction:
      "Install automated temperature monitoring devices in all cold storage areas",
    preventiveAction:
      "Implement 24/7 monitoring dashboard with SMS/email alerts for temperature deviations",
    targetCompletionDate: "2026-03-15",
    assignedTo: "Facilities Team",
    reviewer: "QA Manager",
    createdAt: "2026-01-25T10:00:00",
    updatedAt: "2026-01-25T14:30:00",
  },
  {
    id: "2",
    capaId: "CAPA-2026-002",
    title: "Granulation Process Optimization",
    description:
      "Revise granulation process to prevent moisture content issues",
    type: "Corrective",
    source: "Deviation",
    status: "Verification",
    initiatedBy: "Dr. Emma Wilson",
    initiatedDate: "2026-01-24",
    department: "Production",
    relatedDeviationId: "DEV-2026-002",
    problemStatement:
      "Out of specification dissolution test due to granulation moisture",
    rootCause:
      "Inadequate drying time and temperature control during granulation",
    correctiveAction:
      "Update granulation SOP with specific moisture testing requirements and drying parameters",
    preventiveAction:
      "Install inline moisture analyzer for real-time monitoring",
    targetCompletionDate: "2026-02-28",
    actualCompletionDate: "2026-01-22",
    assignedTo: "Production Manager",
    reviewer: "QA Director",
    approver: "Technical Director",
    effectivenessCheckDate: "2026-03-15",
    createdAt: "2026-01-24T09:15:00",
    updatedAt: "2026-01-25T11:20:00",
  },
  {
    id: "3",
    capaId: "CAPA-2026-003",
    title: "Tablet Press Preventive Maintenance Enhancement",
    description: "Enhance preventive maintenance program for tablet presses",
    type: "Both",
    source: "Deviation",
    status: "Closed",
    initiatedBy: "Maintenance Supervisor",
    initiatedDate: "2026-01-16",
    department: "Maintenance",
    relatedDeviationId: "DEV-2026-003",
    problemStatement: "Tablet press failure due to worn compression rollers",
    rootCause:
      "Insufficient preventive maintenance frequency and wear monitoring",
    correctiveAction: "Replaced worn compression rollers on all tablet presses",
    preventiveAction:
      "Implemented weekly visual inspection checklist and monthly compression force verification",
    targetCompletionDate: "2026-01-30",
    actualCompletionDate: "2026-01-23",
    assignedTo: "Maintenance Team",
    reviewer: "Production Manager",
    approver: "QA Director",
    effectivenessCheckDate: "2026-02-23",
    effectivenessResult: "Effective",
    createdAt: "2026-01-16T13:00:00",
    updatedAt: "2026-01-24T16:45:00",
  },
  {
    id: "4",
    capaId: "CAPA-2026-004",
    title: "Supplier COA Verification Process",
    description: "Implement automated COA tracking and verification system",
    type: "Preventive",
    source: "Internal Review",
    status: "Action Plan Pending",
    initiatedBy: "Procurement Manager",
    initiatedDate: "2026-01-25",
    department: "Supply Chain",
    problemStatement:
      "Delayed COA receipt causing material quarantine and production delays",
    rootCause: "Manual COA tracking without automated reminders",
    targetCompletionDate: "2026-03-01",
    assignedTo: "IT & Procurement Teams",
    createdAt: "2026-01-25T15:30:00",
    updatedAt: "2026-01-25T15:30:00",
  },
  {
    id: "5",
    capaId: "CAPA-2025-089",
    title: "GMP Documentation Training Program",
    description: "Develop comprehensive GMP documentation training module",
    type: "Preventive",
    source: "Self-Identified",
    status: "Closed",
    initiatedBy: "Training Manager",
    initiatedDate: "2025-12-01",
    department: "Quality Assurance",
    problemStatement:
      "Recurring documentation errors and incomplete batch records",
    rootCause: "Insufficient training on GMP documentation requirements",
    correctiveAction: "Provided immediate training to all production operators",
    preventiveAction:
      "Developed comprehensive GMP documentation training module with quarterly refreshers and competency assessments",
    targetCompletionDate: "2026-01-15",
    actualCompletionDate: "2026-01-10",
    assignedTo: "Training Department",
    reviewer: "QA Manager",
    approver: "QA Director",
    effectivenessCheckDate: "2026-02-10",
    effectivenessResult: "Effective",
    createdAt: "2025-12-01T10:00:00",
    updatedAt: "2026-01-10T14:00:00",
  },
];
