import { SystemConfig } from './types';

export const MOCK_SYSTEM_CONFIG: SystemConfig = {
  general: {
    systemName: 'EQMS Enterprise',
    systemDisplayName: 'EQMS - Quality Management System',
    systemLogo: '/assets/logo.png',
    systemFavicon: '/assets/favicon.ico',
    adminEmail: 'admin@eqms.com',
    maintenanceMode: false,
    dateTimeFormat: 'DD/MM/YYYY HH:mm:ss',
    timeZone: 'UTC+7',
    companyInfo: {
      companyName: 'ACME Corporation',
      companyAddress: '123 Business Street, Tech City, TC 12345',
      companyPhone: '+1-555-0123',
      companyWebsite: 'https://www.acme-corp.com',
      taxId: 'TAX-123456789',
      industry: 'Pharmaceutical Manufacturing',
      regulatoryBody: 'FDA, ISO 9001:2015',
    },
    backupSettings: {
      enableAutoBackup: true,
      backupFrequency: 'daily',
      backupTime: '02:00',
      retentionDays: 30,
      backupLocation: 'cloud',
      notifyOnBackupFailure: true,
    },
  },
  security: {
    passwordMinLength: 12,
    requireSpecialChars: true,
    requireNumbers: true,
    requireUppercase: true,
    requireLowercase: true,
    passwordExpiryDays: 90,
    enablePasswordExpiry: true,
    preventPasswordReuse: true,
    passwordHistoryCount: 5,
    sessionTimeoutMinutes: 30,
    enable2FA: true,
    enableAutoLogout: true,
    autoLogoutMinutes: 15,
    enableAccountLockout: true,
    maxLoginAttempts: 5,
    ipSecurity: {
      enableIpWhitelisting: false,
      whitelistedIps: [],
      enableGeoBlocking: false,
      blockedCountries: [],
      allowVpnConnections: true,
    },
    auditSettings: {
      enableDetailedAuditLog: true,
      logLevel: 'standard',
      retainLogsForDays: 365,
      logSensitiveData: false,
      enableRealTimeAlerts: true,
      alertOnSuspiciousActivity: true,
    },
  },
  documents: {
    defaultRetentionPeriodDays: 365,
    enableWatermark: true,
    allowDownload: false,
    maxFileSizeMB: 25,
    versionControl: {
      enableAutoVersioning: true,
      maxVersionsToKeep: 10,
      compareVersionsEnabled: true,
      requireVersionNotes: true,
      majorMinorVersioning: true,
    },
    eSignature: {
      enableESignature: true,
      requirePasswordForSigning: true,
      allowDigitalCertificates: false,
      signingMethods: ['password', 'otp'],
      enforceSigningOrder: true,
      signatureValidityDays: 365,
    },
  },
  notifications: {
    enableEmailNotifications: true,
    enableInAppNotifications: true,
    enableTelegramNotifications: false,
    enableWhatsAppNotifications: false,
    emailDigestFrequency: 'daily',
    emailConfig: {
      smtpHost: 'smtp.gmail.com',
      smtpPort: 587,
      smtpUsername: 'noreply@eqms.com',
      smtpPassword: '••••••••••••',
      senderEmail: 'noreply@eqms.com',
      senderName: 'EQMS Notification',
      useSSL: true,
    },
    telegramConfig: {
      botToken: '',
      chatId: '',
    },
    whatsappConfig: {
      phoneNumberId: '',
      accessToken: '',
      businessAccountId: '',
    },
    smsConfig: {
      enableSms: false,
      provider: 'twilio',
      accountSid: '',
      authToken: '',
      fromNumber: '',
      rateLimitPerHour: 100,
    },
    enableCustomTemplates: false,
    templates: [],
    triggers: {
      documentApproval: true,
      taskAssignment: true,
      systemAlerts: true,
      capaDue: true,
    },
  },
};
