import type { DocumentType, DocumentStatus } from "@/features/documents/types";

export interface Document {
  id: string;
  documentId: string;
  title: string;
  type: DocumentType;
  version: string;
  status: DocumentStatus;
  effectiveDate: string;
  validUntil: string;
  author: string;
  department: string;
  created: string;
  openedBy: string;
  description?: string;
  hasRelatedDocuments?: boolean;
  hasCorrelatedDocuments?: boolean;
  isTemplate?: boolean;
}

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: "1",
    documentId: "SOP.0001.03",
    title: "Standard Operating Procedure for Quality Control Testing",
    type: "SOP",
    version: "3.0",
    status: "Active",
    effectiveDate: "2023-06-15",
    validUntil: "2024-06-15",
    author: "Dr. Sarah Johnson",
    department: "Quality Assurance",
    created: "2023-05-01",
    openedBy: "QA Admin",
    description: "Comprehensive procedure for conducting quality control tests on pharmaceutical products",
    hasRelatedDocuments: true,
    hasCorrelatedDocuments: true,
    isTemplate: true,
  },
  {
    id: "2",
    documentId: "POL.0005.02",
    title: "Quality Management System Policy",
    type: "Policy",
    version: "2.1",
    status: "Draft",
    effectiveDate: "2023-08-01",
    validUntil: "2024-08-01",
    author: "Michael Chen",
    department: "Quality Management",
    created: "2023-07-10",
    openedBy: "System Admin",
    description: "Organization-wide quality management policy framework",
    hasRelatedDocuments: false,
    hasCorrelatedDocuments: false,
  },
  {
    id: "3",
    documentId: "SOP.0012.04",
    title: "Batch Production Record Procedure",
    type: "SOP",
    version: "4.2",
    status: "Active",
    effectiveDate: "2023-09-10",
    validUntil: "2024-09-10",
    author: "Emma Williams",
    department: "Production",
    created: "2023-08-20",
    openedBy: "Production Lead",
    description: "Guidelines for maintaining and reviewing batch production records",
    hasRelatedDocuments: true,
    hasCorrelatedDocuments: false,
    isTemplate: true,
  },
  {
    id: "4",
    documentId: "FORM.0001.01",
    title: "Deviation Report Form",
    type: "Form",
    version: "1.5",
    status: "Obsoleted",
    effectiveDate: "2022-05-20",
    validUntil: "2023-05-20",
    author: "John Davis",
    department: "Quality Assurance",
    created: "2022-04-15",
    openedBy: "QA Manager",
    hasRelatedDocuments: false,
    hasCorrelatedDocuments: true,
  },
  {
    id: "5",
    documentId: "SPEC.0045.02",
    title: "Raw Material Specification - API Grade A",
    type: "Specification",
    version: "2.0",
    status: "Active",
    effectiveDate: "2023-07-01",
    validUntil: "2024-07-01",
    author: "Dr. Lisa Park",
    department: "Quality Control",
    created: "2023-06-01",
    openedBy: "QC Supervisor",
    hasRelatedDocuments: true,
    hasCorrelatedDocuments: true,
  },
  {
    id: "6",
    documentId: "PROT.0008.03",
    title: "Cleaning Validation Protocol",
    type: "Protocol",
    version: "3.1",
    status: "Draft",
    effectiveDate: "2023-04-15",
    validUntil: "2024-04-15",
    author: "Robert Taylor",
    department: "Validation",
    created: "2023-03-10",
    openedBy: "Validation Team",
    hasRelatedDocuments: false,
    hasCorrelatedDocuments: false,
  },
  {
    id: "7",
    documentId: "REP.0001.01",
    title: "Internal Audit Report Q2 2023",
    type: "Report",
    version: "1.0",
    status: "Closed - Cancelled",
    effectiveDate: "2023-06-30",
    validUntil: "2024-06-30",
    author: "Amanda Martinez",
    department: "Quality Assurance",
    created: "2023-06-20",
    openedBy: "Audit Team",
    hasRelatedDocuments: true,
    hasCorrelatedDocuments: false,
  },
  {
    id: "8",
    documentId: "SOP.0023.05",
    title: "Equipment Calibration Procedure",
    type: "SOP",
    version: "5.0",
    status: "Active",
    effectiveDate: "2023-08-15",
    validUntil: "2024-08-15",
    author: "David Brown",
    department: "Engineering",
    created: "2023-07-25",
    openedBy: "Engineering Lead",
    hasRelatedDocuments: false,
    hasCorrelatedDocuments: true,
  },
  {
    id: "9",
    documentId: "SOP.0007.02",
    title: "Training Management Standard Operating Procedure",
    type: "SOP",
    version: "2.3",
    status: "Draft",
    effectiveDate: "2023-10-01",
    validUntil: "2024-10-01",
    author: "Jessica Lee",
    department: "Human Resources",
    created: "2023-09-15",
    openedBy: "HR Manager",
    hasCorrelatedDocuments: false,
  },
  {
    id: "10",
    documentId: "POL.0002.01",
    title: "Data Integrity Policy",
    type: "Policy",
    version: "1.0",
    status: "Obsoleted",
    effectiveDate: "2022-09-01",
    validUntil: "2023-09-01",
    author: "Dr. Sarah Johnson",
    department: "Quality Management",
    created: "2022-08-10",
    openedBy: "QM Director",
    hasCorrelatedDocuments: true,
  },
  {
    id: "11",
    documentId: "SOP.0015.04",
    title: "Good Manufacturing Practice Guidelines",
    type: "SOP",
    version: "4.2",
    status: "Closed - Cancelled",
    effectiveDate: "2023-10-15",
    validUntil: "2024-10-15",
    author: "Michael Chen",
    department: "Manufacturing",
    created: "2023-09-01",
    openedBy: "Manufacturing Manager",
    description: "Comprehensive GMP guidelines for pharmaceutical manufacturing",
    hasCorrelatedDocuments: false,
  },
  {
    id: "12",
    documentId: "SOP-QA-001",
    title: "Standard Operating Procedure for Quality Control Testing",
    type: "SOP",
    version: "1.0",
    status: "Active",
    effectiveDate: "2026-02-01",
    validUntil: "2028-02-01",
    author: "John Smith",
    department: "Quality Assurance",
    created: "2026-01-05",
    openedBy: "Nguyen Van A",
    description: "This SOP outlines the procedures for quality control testing of pharmaceutical products.",
    hasRelatedDocuments: false,
    hasCorrelatedDocuments: true,
  },
  {
    id: "13",
    documentId: "SOP-QA-002",
    title: "Quality Assurance Documentation Standards",
    type: "SOP",
    version: "2.0",
    status: "Draft",
    effectiveDate: "2026-02-05",
    validUntil: "2028-02-05",
    author: "Jane Doe",
    department: "Quality Assurance",
    created: "2026-01-06",
    openedBy: "Nguyen Van A",
    description: "Standards for maintaining QA documentation in compliance with regulatory requirements.",
    hasRelatedDocuments: true,
    hasCorrelatedDocuments: false,
  },
  {
    id: "14",
    documentId: "SOP-QA-003",
    title: "Environmental Monitoring Procedures",
    type: "SOP",
    version: "1.5",
    status: "Obsoleted",
    effectiveDate: "2026-02-10",
    validUntil: "2028-02-10",
    author: "Robert Lee",
    department: "Quality Assurance",
    created: "2026-01-07",
    openedBy: "Nguyen Van A",
    description: "Procedures for environmental monitoring in controlled manufacturing areas.",
    hasRelatedDocuments: false,
    hasCorrelatedDocuments: true,
  },
  {
    id: "15",
    documentId: "SOP-QA-004",
    title: "Calibration and Maintenance of Equipment",
    type: "SOP",
    version: "3.0",
    status: "Closed - Cancelled",
    effectiveDate: "2026-02-15",
    validUntil: "2028-02-15",
    author: "Emily Chen",
    department: "Quality Assurance",
    created: "2026-01-08",
    openedBy: "Nguyen Van A",
    description: "Guidelines for calibration and preventive maintenance of laboratory equipment.",
    hasRelatedDocuments: true,
    hasCorrelatedDocuments: true,
  },
  {
    id: "16",
    documentId: "SOP-QA-005",
    title: "Deviation Management Procedures",
    type: "SOP",
    version: "1.0",
    status: "Active",
    effectiveDate: "2026-02-20",
    validUntil: "2028-02-20",
    author: "David Park",
    department: "Quality Assurance",
    created: "2026-01-09",
    openedBy: "Nguyen Van A",
    description: "Procedures for identifying, investigating, and resolving deviations from SOPs.",
    hasRelatedDocuments: false,
    hasCorrelatedDocuments: false,
  },
  {
    id: "17",
    documentId: "SOP-QA-006",
    title: "Change Control Procedures",
    type: "SOP",
    version: "2.1",
    status: "Draft",
    effectiveDate: "2026-03-01",
    validUntil: "2028-03-01",
    author: "Sarah Jones",
    department: "Quality Assurance",
    created: "2026-01-15",
    openedBy: "Nguyen Van A",
    description: "Procedures for managing changes to documents, equipment, and processes.",
    hasRelatedDocuments: true,
    hasCorrelatedDocuments: true,
  },
  {
    id: "18",
    documentId: "SOP-QA-007",
    title: "Customer Complaint Handling",
    type: "SOP",
    version: "1.3",
    status: "Active",
    effectiveDate: "2026-03-05",
    validUntil: "2028-03-05",
    author: "Mike Brown",
    department: "Quality Assurance",
    created: "2026-01-20",
    openedBy: "Nguyen Van A",
    description: "Procedures for receiving, investigating, and resolving customer complaints.",
    hasRelatedDocuments: false,
    hasCorrelatedDocuments: false,
  },
  {
    id: "19",
    documentId: "SOP-QA-008",
    title: "Vendor Qualification",
    type: "SOP",
    version: "3.2",
    status: "Obsoleted",
    effectiveDate: "2026-03-10",
    validUntil: "2028-03-10",
    author: "Lisa Wilson",
    department: "Quality Assurance",
    created: "2026-01-25",
    openedBy: "Nguyen Van A",
    description: "Procedures for qualifying and monitoring vendors of raw materials and services.",
    hasRelatedDocuments: true,
    hasCorrelatedDocuments: false,
  },
  {
    id: "20",
    documentId: "SOP-QA-009",
    title: "Product Recall Procedures",
    type: "SOP",
    version: "1.1",
    status: "Closed - Cancelled",
    effectiveDate: "2026-03-15",
    validUntil: "2028-03-15",
    author: "Tom Clark",
    department: "Quality Assurance",
    created: "2026-01-30",
    openedBy: "Nguyen Van A",
    description: "Procedures for initiating and managing product recalls.",
    hasRelatedDocuments: false,
  }
];
