import type { TrainingRecord, TrainingFile, TrainingStatus } from "../../types";

// Mock training files
export const MOCK_TRAINING_FILES: TrainingFile[] = [
  {
    id: "tf-001",
    file: null as any,
    name: "GMP_Training_Materials_2026.pdf",
    size: 2456789,
    type: "application/pdf",
    progress: 100,
    status: "success",
  },
  {
    id: "tf-002",
    file: null as any,
    name: "GMP_Presentation_Slides.pptx",
    size: 8765432,
    type: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    progress: 100,
    status: "success",
  },
  {
    id: "tf-003",
    file: null as any,
    name: "Quick_Reference_Guide.docx",
    size: 567890,
    type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    progress: 100,
    status: "success",
  },
];

// Mock courses — in real app, fetch from API by ID
export const MOCK_COURSES: (TrainingRecord & {
  trainingFiles: TrainingFile[];
  instruction: string;
  examTemplate?: string;
  answerKey?: string;
  passingGradeType?: "pass_fail" | "score_10" | "percentage";
  maxAttempts?: number;
  questions: any[];
  instructorType: "internal" | "external";
  distributionList: string[];
  linkedDocumentId: string;
  linkedDocumentTitle: string;
})[] = [
  {
    id: "1",
    trainingId: "TRN-2026-001",
    title: "GMP Basic Principles",
    description:
      "This comprehensive training covers the fundamental principles of Good Manufacturing Practice (GMP) required for all personnel working in pharmaceutical manufacturing environments.",
    type: "GMP",
    trainingMethod: "Quiz (Paper-based/Manual)",
    status: "In-Progress",
    instructor: "Dr. Sarah Williams",
    instructorType: "internal",
    scheduledDate: "2026-03-15",
    duration: 4,
    location: "Training Room A",
    capacity: 25,
    enrolled: 20,
    department: "Quality Assurance",
    mandatory: true,
    passScore: 80,
    recurrence: { enabled: true, intervalMonths: 12 },
    linkedDocumentId: "DOC-001",
    linkedDocumentTitle: "SOP-QA-001: Good Manufacturing Practices",
    distributionList: ["Quality Assurance", "Production", "Quality Control"],
    trainingFiles: MOCK_TRAINING_FILES,
    instruction:
      "Focus on Chapter 3 (Cleaning Validation) and Appendix B (Equipment Handling). Review all SOPs referenced in Section 2.4 before the training session.",
    examTemplate: "GMP_Exam_Template_2026.pdf",
    answerKey: "GMP_Answer_Key_2026.pdf",
    passingGradeType: "score_10",
    maxAttempts: 3,
    questions: [
      {
        id: "q1",
        text: "What is the primary purpose of GMP?",
        type: "multiple_choice",
        points: 10,
        options: [
          { id: "a", text: "To increase production speed", isCorrect: false },
          { id: "b", text: "To ensure product quality and safety", isCorrect: true },
          { id: "c", text: "To reduce manufacturing costs", isCorrect: false },
          { id: "d", text: "To improve employee satisfaction", isCorrect: false },
        ],
      },
    ],
    createdBy: "Admin",
    createdAt: "2026-01-15",
    updatedAt: "2026-01-20",
  },
  {
    id: "2",
    trainingId: "TRN-2026-002",
    title: "Cleanroom Qualification",
    description:
      "Training on cleanroom classification, gowning procedures, and environmental monitoring requirements.",
    type: "Technical",
    trainingMethod: "Read & Understood",
    status: "Scheduled",
    instructor: "Michael Chen",
    instructorType: "internal",
    scheduledDate: "2026-03-20",
    duration: 2,
    location: "Cleanroom Facility",
    capacity: 15,
    enrolled: 15,
    department: "Production",
    mandatory: true,
    passScore: 100,
    recurrence: { enabled: false, intervalMonths: 0 },
    linkedDocumentId: "DOC-002",
    linkedDocumentTitle: "SOP-CR-002: Cleanroom Operations",
    distributionList: ["Production", "Quality Control"],
    trainingFiles: [
      {
        id: "tf-004",
        file: null as any,
        name: "Cleanroom_SOP_Manual.pdf",
        size: 3456789,
        type: "application/pdf",
        progress: 100,
        status: "success",
      },
    ],
    instruction:
      "Pay special attention to gowning procedures in Section 3 and environmental monitoring protocols in Section 5.",
    passingGradeType: "pass_fail",
    maxAttempts: 1,
    questions: [],
    createdBy: "QA Manager",
    createdAt: "2026-01-10",
    updatedAt: "2026-01-25",
  },
  {
    id: "3",
    trainingId: "TRN-2026-003",
    title: "Emergency Response Procedures",
    description:
      "Training on fire safety, chemical spill response, and emergency evacuation procedures aligned with OSHA guidelines.",
    type: "Safety",
    trainingMethod: "Hands-on/OJT",
    status: "Completed",
    instructor: "Robert Lee",
    instructorType: "external",
    scheduledDate: "2026-01-20",
    duration: 6,
    location: "Assembly Point A",
    capacity: 50,
    enrolled: 45,
    department: "All Departments",
    mandatory: true,
    passScore: 70,
    recurrence: { enabled: true, intervalMonths: 6 },
    linkedDocumentId: "DOC-003",
    linkedDocumentTitle: "SOP-HSE-001: Emergency Response Plan",
    distributionList: ["All Departments"],
    trainingFiles: [
      {
        id: "tf-005",
        file: null as any,
        name: "Emergency_Response_Guide.pdf",
        size: 4567890,
        type: "application/pdf",
        progress: 100,
        status: "success",
      },
    ],
    instruction: "Complete all fire extinguisher drills during hands-on session.",
    questions: [],
    createdBy: "HSE Manager",
    createdAt: "2026-01-05",
    updatedAt: "2026-01-21",
  },
];

// --- Mock Data ---
export const MOCK_TRAININGS: TrainingRecord[] = [
  {
    id: "1",
    trainingId: "TRN-2026-001",
    title: "GMP Basic Principles",
    description: "Introduction to Good Manufacturing Practices",
    type: "GMP",
    trainingMethod: "Quiz (Paper-based/Manual)",
    status: "In-Progress",
    instructor: "John Smith",
    scheduledDate: "2026-02-15",
    duration: 4,
    location: "Training Room A",
    capacity: 30,
    enrolled: 25,
    department: "Quality Assurance",
    mandatory: true,
    passScore: 80,
    createdBy: "Admin",
    createdAt: "2026-01-15",
    updatedAt: "2026-01-20",
  },
  {
    id: "2",
    trainingId: "TRN-2026-002",
    title: "Cleanroom Qualification",
    description: "Training on cleanroom operations and aseptic techniques",
    type: "Technical",
    trainingMethod: "Hands-on/OJT",
    status: "Scheduled",
    instructor: "Sarah Johnson",
    scheduledDate: "2026-01-26",
    duration: 3,
    location: "Cleanroom B",
    capacity: 20,
    enrolled: 20,
    department: "Quality Assurance",
    mandatory: true,
    passScore: 85,
    createdBy: "QA Manager",
    createdAt: "2026-01-10",
    updatedAt: "2026-01-25",
  },
  {
    id: "3",
    trainingId: "TRN-2026-003",
    title: "HPLC Operation Advanced",
    description: "Advanced techniques for HPLC operation and troubleshooting",
    type: "Technical",
    trainingMethod: "Hands-on/OJT",
    status: "Completed",
    instructor: "Dr. Michael Chen",
    scheduledDate: "2026-01-20",
    duration: 6,
    location: "Laboratory 2",
    capacity: 15,
    enrolled: 14,
    department: "QC Lab",
    mandatory: false,
    passScore: 75,
    createdBy: "Lab Supervisor",
    createdAt: "2026-01-05",
    updatedAt: "2026-01-21",
  },
  {
    id: "4",
    trainingId: "TRN-2026-004",
    title: "ISO 9001:2015 Requirements",
    description:
      "Understanding ISO 9001 quality management system requirements",
    type: "Compliance",
    trainingMethod: "Read & Understood",
    status: "Scheduled",
    instructor: "Emma Wilson",
    scheduledDate: "2026-03-01",
    duration: 8,
    location: "Conference Hall",
    capacity: 40,
    enrolled: 15,
    department: "All Departments",
    mandatory: false,
    passScore: 70,
    createdBy: "QA Director",
    createdAt: "2026-01-15",
    updatedAt: "2026-01-23",
  },
  {
    id: "5",
    trainingId: "TRN-2026-005",
    title: "SOP Review & Update Procedures",
    description: "Training on proper SOP review and revision processes",
    type: "SOP",
    trainingMethod: "Read & Understood",
    status: "Overdue",
    instructor: "David Brown",
    scheduledDate: "2026-01-10",
    duration: 2,
    location: "Meeting Room 3",
    capacity: 25,
    enrolled: 18,
    department: "Documentation",
    mandatory: true,
    passScore: 80,
    createdBy: "Doc Control",
    createdAt: "2025-12-20",
    updatedAt: "2026-01-05",
  },
];
