import type { Notification } from "./types";

// --- Mock Data ---
export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "1",
    type: "review-request",
    title: "Document Review Request",
    description: "John Smith requested your review on SOP-QA-015",
    module: "Document",
    priority: "high",
    status: "unread",
    createdAt: "2026-01-29T08:30:00Z",
    sender: { id: "u1", name: "John Smith" },
    relatedItem: {
      id: "doc1",
      type: "document",
      code: "SOP-QA-015",
      title: "Quality Assurance Procedures",
    },
    actionUrl: "/documents/doc1/review",
  },
  {
    id: "2",
    type: "approval",
    title: "Document Approved",
    description: "Sarah Johnson approved DEV-2023-089",
    module: "Deviation",
    priority: "medium",
    status: "unread",
    createdAt: "2026-01-29T07:45:00Z",
    sender: { id: "u2", name: "Sarah Johnson" },
    relatedItem: {
      id: "dev1",
      type: "deviation",
      code: "DEV-2023-089",
      title: "Temperature Excursion Investigation",
    },
    actionUrl: "/deviations-ncs",
  },
  {
    id: "3",
    type: "capa-assignment",
    title: "CAPA Assignment",
    description: "You were assigned to CAPA-2023-045",
    module: "CAPA",
    priority: "critical",
    status: "unread",
    createdAt: "2026-01-29T06:00:00Z",
    relatedItem: {
      id: "capa1",
      type: "capa",
      code: "CAPA-2023-045",
      title: "Packaging Defect Corrective Action",
    },
    actionUrl: "/capa-management",
  },
  {
    id: "4",
    type: "training-completion",
    title: "Training Completed",
    description: "Mike Wilson completed training on GMP Basics",
    module: "Training",
    priority: "low",
    status: "read",
    createdAt: "2026-01-28T14:30:00Z",
    readAt: "2026-01-28T16:00:00Z",
    sender: { id: "u3", name: "Mike Wilson" },
    relatedItem: {
      id: "trn1",
      type: "training",
      code: "TRN-2025-055",
      title: "GMP Basics Annual Training",
    },
    actionUrl: "/training-management",
  },
  {
    id: "5",
    type: "document-update",
    title: "Document Updated",
    description: "Quality Team updated SOP-QA-001",
    module: "Document",
    priority: "medium",
    status: "read",
    createdAt: "2026-01-28T10:15:00Z",
    readAt: "2026-01-28T11:30:00Z",
    sender: { id: "u4", name: "Quality Team" },
    relatedItem: {
      id: "doc2",
      type: "document",
      code: "SOP-QA-001",
      title: "Quality Management System Overview",
    },
    actionUrl: "/documents/doc2",
  },
  {
    id: "6",
    type: "comment-reply",
    title: "Comment Reply",
    description: "Emma Davis replied to your comment on Document Review Process",
    module: "Document",
    priority: "low",
    status: "read",
    createdAt: "2026-01-27T16:45:00Z",
    readAt: "2026-01-27T18:00:00Z",
    sender: { id: "u5", name: "Emma Davis" },
  },
  {
    id: "7",
    type: "review-request",
    title: "CAPA Review Request",
    description: "Lisa Chen requested your review on CAPA-2023-078",
    module: "CAPA",
    priority: "high",
    status: "unread",
    createdAt: "2026-01-27T09:30:00Z",
    sender: { id: "u6", name: "Lisa Chen" },
    relatedItem: {
      id: "capa2",
      type: "capa",
      code: "CAPA-2023-078",
      title: "Equipment Calibration Failure",
    },
    actionUrl: "/capa-management",
  },
  {
    id: "8",
    type: "document-update",
    title: "Document Published",
    description: "Regulatory Team published SOP-REG-003",
    module: "Document",
    priority: "medium",
    status: "read",
    createdAt: "2026-01-26T14:00:00Z",
    readAt: "2026-01-26T15:30:00Z",
    sender: { id: "u7", name: "Regulatory Team" },
    relatedItem: {
      id: "doc3",
      type: "document",
      code: "SOP-REG-003",
      title: "Regulatory Submission Guidelines",
    },
    actionUrl: "/documents/doc3",
  },
  {
    id: "9",
    type: "training-completion",
    title: "Training Completed",
    description: "David Brown completed training on Deviation Handling",
    module: "Training",
    priority: "low",
    status: "read",
    createdAt: "2026-01-25T11:20:00Z",
    readAt: "2026-01-25T12:00:00Z",
    sender: { id: "u8", name: "David Brown" },
    relatedItem: {
      id: "trn2",
      type: "training",
      code: "TRN-2025-060",
      title: "Deviation Handling Procedures",
    },
    actionUrl: "/training-management",
  },
  {
    id: "10",
    type: "approval",
    title: "Change Control Approved",
    description: "Maria Garcia approved CHG-2023-156",
    module: "Change Control",
    priority: "high",
    status: "read",
    createdAt: "2026-01-24T16:30:00Z",
    readAt: "2026-01-24T17:00:00Z",
    sender: { id: "u9", name: "Maria Garcia" },
    relatedItem: {
      id: "chg1",
      type: "change-control",
      code: "CHG-2023-156",
      title: "Production Line Modification",
    },
    actionUrl: "/change-management",
  },
  {
    id: "11",
    type: "deviation-assignment",
    title: "Urgent Deviation Assignment",
    description: "You were assigned to DEV-2023-234",
    module: "Deviation",
    priority: "critical",
    status: "unread",
    createdAt: "2026-01-23T08:00:00Z",
    relatedItem: {
      id: "dev2",
      type: "deviation",
      code: "DEV-2023-234",
      title: "Critical Equipment Failure",
    },
    actionUrl: "/deviations-ncs",
  },
  {
    id: "12",
    type: "document-update",
    title: "Batch Record Updated",
    description: "Production Team updated BP-PROD-045",
    module: "Document",
    priority: "medium",
    status: "read",
    createdAt: "2026-01-22T13:45:00Z",
    readAt: "2026-01-22T14:30:00Z",
    sender: { id: "u10", name: "Production Team" },
    relatedItem: {
      id: "doc4",
      type: "document",
      code: "BP-PROD-045",
      title: "Batch Production Record Template",
    },
    actionUrl: "/documents/doc4",
  },
];
