import { Supplier } from "./types";

// ============================================================================
// MOCK DATA
// ============================================================================
export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: "1",
    supplierId: "SUP-001",
    name: "PharmaChem AG",
    category: "API Manufacturer",
    status: "Qualified",
    riskRating: "Low",
    country: "Switzerland",
    city: "Basel",
    contactPerson: "Dr. Stefan Hoffmann",
    email: "s.hoffmann@pharmachem.ch",
    phone: "+41 61 555 0100",
    qualificationDate: "2024-03-15",
    lastAuditDate: "2025-09-20",
    nextAuditDate: "2026-09-20",
    suppliedMaterials: ["Amoxicillin Trihydrate", "Cephalexin"],
    gmpCertificate: "GMP-CH-2025-001",
    qualityAgreement: true,
    responsiblePerson: "QA Director",
    createdAt: "2024-03-15T10:00:00",
    updatedAt: "2025-12-01T09:00:00",
  },
  {
    id: "2",
    supplierId: "SUP-002",
    name: "PackSolutions GmbH",
    category: "Packaging Material",
    status: "Qualified",
    riskRating: "Low",
    country: "Germany",
    city: "Munich",
    contactPerson: "Ingrid Bauer",
    email: "i.bauer@packsolutions.de",
    phone: "+49 89 555 0200",
    qualificationDate: "2023-06-10",
    lastAuditDate: "2025-06-10",
    nextAuditDate: "2026-06-10",
    suppliedMaterials: ["PVC/Alu Blisters", "Cartons", "Labels"],
    qualityAgreement: true,
    responsiblePerson: "Procurement Manager",
    createdAt: "2023-06-10T08:00:00",
    updatedAt: "2025-11-15T14:30:00",
  },
  {
    id: "3",
    supplierId: "SUP-003",
    name: "BioTest Labs S.r.l.",
    category: "Laboratory Service",
    status: "Under Evaluation",
    riskRating: "Medium",
    country: "Italy",
    city: "Milan",
    contactPerson: "Dr. Marco Rossi",
    email: "m.rossi@biotestlabs.it",
    phone: "+39 02 555 0300",
    suppliedMaterials: ["Microbial Testing", "Endotoxin Testing"],
    qualityAgreement: false,
    responsiblePerson: "QC Director",
    createdAt: "2026-01-10T09:00:00",
    updatedAt: "2026-01-20T11:00:00",
  },
  {
    id: "4",
    supplierId: "SUP-004",
    name: "Excipi Corp",
    category: "Excipient Supplier",
    status: "Conditionally Approved",
    riskRating: "Medium",
    country: "France",
    city: "Lyon",
    contactPerson: "Pierre Dubois",
    email: "p.dubois@excipicorp.fr",
    phone: "+33 4 555 0400",
    qualificationDate: "2025-08-20",
    lastAuditDate: "2025-08-15",
    nextAuditDate: "2026-02-15",
    suppliedMaterials: ["Lactose Monohydrate", "Microcrystalline Cellulose", "Magnesium Stearate"],
    gmpCertificate: "GMP-FR-2025-042",
    qualityAgreement: true,
    responsiblePerson: "QA Manager",
    createdAt: "2025-08-20T10:00:00",
    updatedAt: "2026-01-15T09:00:00",
  },
  {
    id: "5",
    supplierId: "SUP-005",
    name: "ColdTrans Logistics B.V.",
    category: "Logistics Provider",
    status: "Suspended",
    riskRating: "High",
    country: "Netherlands",
    city: "Rotterdam",
    contactPerson: "Jan van der Berg",
    email: "j.vanderberg@coldtrans.nl",
    phone: "+31 10 555 0500",
    qualificationDate: "2023-01-20",
    lastAuditDate: "2025-07-10",
    nextAuditDate: "2026-01-10",
    suppliedMaterials: ["Cold Chain Distribution", "GDP Transport"],
    gdpCertificate: "GDP-NL-2024-078",
    qualityAgreement: true,
    responsiblePerson: "Supply Chain Director",
    createdAt: "2023-01-20T10:00:00",
    updatedAt: "2026-01-12T08:00:00",
  },
];
