import { RegulatorySubmission } from "./types";

// ============================================================================
// MOCK DATA
// ============================================================================
export const MOCK_SUBMISSIONS: RegulatorySubmission[] = [
  {
    id: "1",
    submissionId: "REG-2026-001",
    title: "Type II Variation - Amoxicillin Manufacturing Process",
    description: "Update manufacturing process parameters for tablet compression",
    type: "Type II Variation",
    status: "Submitted",
    authority: "EMA",
    relatedProduct: "Amoxicillin Capsules 500mg",
    submissionDate: "2026-01-15",
    targetDate: "2026-07-15",
    referenceNumber: "EMA/2026/VAR-II/001",
    submittedBy: "Dr. Elena Vasquez",
    department: "Regulatory Affairs",
    assignedTo: "RA Team Lead",
    reviewer: "RA Director",
    dossierVersion: "3.2",
    ctdModule: "Module 3 - Quality",
    createdAt: "2026-01-10T09:00:00",
    updatedAt: "2026-01-15T14:30:00",
  },
  {
    id: "2",
    submissionId: "REG-2026-002",
    title: "GMP Certificate Renewal - Site A",
    description: "Annual GMP certificate renewal for manufacturing site A",
    type: "GMP Certificate",
    status: "Under Review",
    authority: "BfArM",
    submissionDate: "2026-01-05",
    targetDate: "2026-04-05",
    referenceNumber: "BfArM/2026/GMP/045",
    submittedBy: "QA Director",
    department: "Quality Assurance",
    assignedTo: "QA Director",
    reviewer: "Site Director",
    createdAt: "2026-01-05T10:00:00",
    updatedAt: "2026-01-20T11:00:00",
  },
  {
    id: "3",
    submissionId: "REG-2026-003",
    title: "PSUR/PBRER - Metformin HCl Tablets",
    description: "Periodic Safety Update Report for marketing authorization renewal",
    type: "PSUR/PBRER",
    status: "Draft",
    authority: "EMA",
    relatedProduct: "Metformin HCl Tablets 850mg",
    targetDate: "2026-03-31",
    submittedBy: "PV Manager",
    department: "Pharmacovigilance",
    assignedTo: "PV Analyst",
    dossierVersion: "1.0",
    ctdModule: "Module 5 - Clinical",
    createdAt: "2026-01-20T08:00:00",
    updatedAt: "2026-01-25T09:00:00",
  },
  {
    id: "4",
    submissionId: "REG-2025-045",
    title: "Marketing Authorization Application - Omeprazole DR Capsules",
    description: "New MAA submission for omeprazole delayed-release capsules 20mg",
    type: "Marketing Authorization Application",
    status: "Approved",
    authority: "EMA",
    relatedProduct: "Omeprazole DR Capsules 20mg",
    submissionDate: "2025-03-15",
    targetDate: "2025-12-15",
    approvalDate: "2025-11-28",
    referenceNumber: "EMA/2025/MAA/098",
    submittedBy: "Dr. Hans Mueller",
    department: "Regulatory Affairs",
    assignedTo: "RA Team Lead",
    reviewer: "RA Director",
    dossierVersion: "1.0",
    ctdModule: "Modules 1-5",
    createdAt: "2025-03-01T10:00:00",
    updatedAt: "2025-11-28T16:00:00",
  },
  {
    id: "5",
    submissionId: "REG-2026-004",
    title: "Type IA Variation - Updated Shelf Life for Ceftriaxone",
    description: "Extend shelf life from 24 to 36 months based on stability data",
    type: "Type IA Variation",
    status: "Questions Received",
    authority: "MHRA",
    relatedProduct: "Ceftriaxone for Injection 1g",
    submissionDate: "2025-12-10",
    targetDate: "2026-03-10",
    referenceNumber: "MHRA/2025/VAR-IA/112",
    submittedBy: "RA Specialist",
    department: "Regulatory Affairs",
    assignedTo: "RA Team Lead",
    reviewer: "RA Director",
    dossierVersion: "2.1",
    ctdModule: "Module 3 - Quality",
    createdAt: "2025-12-05T09:00:00",
    updatedAt: "2026-01-22T08:00:00",
  },
  {
    id: "6",
    submissionId: "REG-2025-038",
    title: "Renewal - Amoxicillin Marketing Authorization",
    description: "5-year renewal of marketing authorization for EU market",
    type: "Renewal",
    status: "Approved",
    authority: "EMA",
    relatedProduct: "Amoxicillin Capsules 500mg",
    submissionDate: "2025-06-01",
    targetDate: "2025-10-01",
    approvalDate: "2025-09-15",
    referenceNumber: "EMA/2025/REN/067",
    submittedBy: "Dr. Elena Vasquez",
    department: "Regulatory Affairs",
    assignedTo: "RA Team Lead",
    reviewer: "RA Director",
    dossierVersion: "4.0",
    createdAt: "2025-05-15T10:00:00",
    updatedAt: "2025-09-15T14:00:00",
  },
];
