import type { ControlledCopy } from './types';

export const MOCK_ALL_CONTROLLED_COPIES: ControlledCopy[] = [
  {
    id: "cc-001",
    documentNumber: "CC-2024-001",
    createdDate: "2024-01-10",
    createdTime: "09:30:45",
    openedBy: "John Smith",
    name: "Standard Operating Procedure for Material Receipt",
    status: "Ready for Distribution",
    validUntil: "2025-01-10",
    document: "SOP.0015.02",
    distributionList: "Warehouse Team, QC Team",
    version: "2.0",
    location: "Warehouse - Receiving",
    department: "Operations",
    reason: "Annual review and update",
  },
  {
    id: "cc-002",
    documentNumber: "CC-2024-002",
    createdDate: "2024-01-08",
    createdTime: "14:22:10",
    openedBy: "Sarah Johnson",
    name: "Work Instruction for Equipment Maintenance",
    status: "Distributed",
    validUntil: "2024-12-31",
    document: "WI.0028.01",
    distributionList: "Maintenance, Production",
    version: "1.0",
    recipientName: "Mike Maintenance",
    distributedDate: "2024-01-09",
    distributedBy: "Document Controller",
    department: "Maintenance",
  },
  {
    id: "cc-003",
    documentNumber: "CC-2024-003",
    createdDate: "2024-01-05",
    createdTime: "11:15:33",
    openedBy: "David Wilson",
    name: "Quality Control Inspection Procedure",
    status: "Obsolete",
    validUntil: "2024-01-05",
    document: "QCP.0112.03",
    distributionList: "QC Department",
    version: "3.0",
    department: "Quality Control",
    reason: "Superseded by new version",
  },
  {
    id: "cc-004",
    documentNumber: "CC-2024-004",
    createdDate: "2024-01-03",
    createdTime: "08:45:20",
    openedBy: "Emily Brown",
    name: "Training Manual for New Operators",
    status: "Closed - Cancelled",
    validUntil: "2024-01-03",
    document: "TM.0045.01",
    distributionList: "HR, Training Team",
    version: "1.0",
    department: "Human Resources",
    reason: "Cancelled due to policy change",
  },
  {
    id: "cc-005",
    documentNumber: "CC-2024-005",
    createdDate: "2024-01-12",
    createdTime: "16:50:12",
    openedBy: "Robert Lee",
    name: "Validation Protocol for Sterilization Process",
    status: "Ready for Distribution",
    validUntil: "2025-06-30",
    document: "VP.0087.02",
    distributionList: "Validation Team, Production",
    version: "2.0",
    location: "Sterilization Area",
    department: "Validation",
  },
  {
    id: "cc-006",
    documentNumber: "CC-2024-006",
    createdDate: "2024-01-11",
    createdTime: "10:20:55",
    openedBy: "Lisa Anderson",
    name: "Cleaning and Sanitization Procedure",
    status: "Distributed",
    validUntil: "2024-12-15",
    document: "SOP.0156.01",
    distributionList: "Cleaning Staff, QA",
    version: "1.0",
    recipientName: "Cleaning Supervisor",
    distributedDate: "2024-01-11",
    distributedBy: "QA Manager",
    department: "Quality Assurance",
  },
  {
    id: "cc-007",
    documentNumber: "CC-2023-089",
    createdDate: "2023-12-20",
    createdTime: "13:40:18",
    openedBy: "Michael Chen",
    name: "Batch Record Template - Legacy",
    status: "Obsolete",
    validUntil: "2023-12-31",
    document: "BRT.0234.05",
    distributionList: "Production, QC",
    version: "5.0",
    department: "Manufacturing",
    reason: "Replaced by new template",
  },
  {
    id: "cc-008",
    documentNumber: "CC-2024-008",
    createdDate: "2024-01-09",
    createdTime: "15:30:42",
    openedBy: "Anna Martinez",
    name: "Equipment Calibration Schedule",
    status: "Ready for Distribution",
    validUntil: "2025-01-09",
    document: "CS.0067.01",
    distributionList: "Calibration Lab, Maintenance",
    version: "1.0",
    location: "Calibration Lab",
    department: "Metrology",
  },
  {
    id: "cc-009",
    documentNumber: "CC-2024-009",
    createdDate: "2024-01-07",
    createdTime: "11:25:30",
    openedBy: "Peter Zhang",
    name: "Environmental Monitoring Procedure",
    status: "Distributed",
    validUntil: "2025-01-07",
    document: "SOP.0234.01",
    distributionList: "QA Team, Production",
    version: "1.0",
    recipientName: "QA Lead",
    distributedDate: "2024-01-08",
    distributedBy: "Quality Manager",
    department: "Quality Assurance",
  },
  {
    id: "cc-010",
    documentNumber: "CC-2023-101",
    createdDate: "2023-11-15",
    createdTime: "14:10:22",
    openedBy: "Jessica White",
    name: "Equipment Qualification Protocol - Old",
    status: "Closed - Cancelled",
    validUntil: "2023-11-15",
    document: "EQP.0156.02",
    distributionList: "Engineering, Validation",
    version: "2.0",
    department: "Engineering",
    reason: "Project cancelled",
  },
  {
    id: "cc-011",
    documentNumber: "CC-2024-011",
    createdDate: "2024-02-01",
    createdTime: "08:15:30",
    openedBy: "Thomas Anderson",
    name: "CAPA Investigation Procedure",
    status: "Ready for Distribution",
    validUntil: "2025-02-01",
    document: "SOP.0245.01",
    distributionList: "Quality Assurance, Production",
    version: "1.0",
    location: "QA Office",
    department: "Quality Assurance",
    reason: "New procedure implementation",
  },
  {
    id: "cc-012",
    documentNumber: "CC-2024-012",
    createdDate: "2024-02-03",
    createdTime: "13:45:12",
    openedBy: "Maria Garcia",
    name: "Deviation Management SOP",
    status: "Distributed",
    validUntil: "2025-02-03",
    document: "SOP.0189.02",
    distributionList: "All Departments",
    version: "2.0",
    recipientName: "Department Heads",
    distributedDate: "2024-02-04",
    distributedBy: "QA Director",
    department: "Quality Assurance",
  },
  {
    id: "cc-013",
    documentNumber: "CC-2024-013",
    createdDate: "2024-02-05",
    createdTime: "09:20:45",
    openedBy: "Robert Johnson",
    name: "Aseptic Processing Guidelines",
    status: "Ready for Distribution",
    validUntil: "2025-08-05",
    document: "SOP.0334.03",
    distributionList: "Manufacturing, QC",
    version: "3.0",
    location: "Aseptic Processing Area",
    department: "Manufacturing",
    reason: "Updated to comply with new regulations",
  },
  {
    id: "cc-014",
    documentNumber: "CC-2024-014",
    createdDate: "2024-02-07",
    createdTime: "14:30:22",
    openedBy: "Jennifer White",
    name: "Laboratory Safety Protocol",
    status: "Distributed",
    validUntil: "2025-02-07",
    document: "PROT.0056.01",
    distributionList: "Laboratory Staff",
    version: "1.0",
    recipientName: "Lab Safety Officer",
    distributedDate: "2024-02-08",
    distributedBy: "Safety Manager",
    department: "Safety & Compliance",
  },
  {
    id: "cc-015",
    documentNumber: "CC-2024-015",
    createdDate: "2024-02-10",
    createdTime: "11:10:55",
    openedBy: "Daniel Kim",
    name: "Supplier Audit Checklist",
    status: "Ready for Distribution",
    validUntil: "2025-02-10",
    document: "FORM.0123.02",
    distributionList: "Supply Chain, QA",
    version: "2.0",
    location: "Supply Chain Office",
    department: "Supply Chain",
    reason: "Enhanced audit requirements",
  },
  {
    id: "cc-016",
    documentNumber: "CC-2024-016",
    createdDate: "2024-02-12",
    createdTime: "10:05:18",
    openedBy: "Susan Miller",
    name: "Change Control Approval Form",
    status: "Distributed",
    validUntil: "2024-12-12",
    document: "FORM.0078.01",
    distributionList: "Change Control Board",
    version: "1.0",
    recipientName: "CCB Members",
    distributedDate: "2024-02-13",
    distributedBy: "Change Control Coordinator",
    department: "Quality Management",
  },
  {
    id: "cc-017",
    documentNumber: "CC-2023-145",
    createdDate: "2023-10-20",
    createdTime: "16:40:12",
    openedBy: "Kevin Brown",
    name: "Old Packaging Specification",
    status: "Obsolete",
    validUntil: "2023-12-20",
    document: "SPEC.0089.04",
    distributionList: "Packaging, QC",
    version: "4.0",
    department: "Packaging",
    reason: "New packaging material approved",
  },
  {
    id: "cc-018",
    documentNumber: "CC-2024-018",
    createdDate: "2024-02-15",
    createdTime: "09:55:30",
    openedBy: "Rachel Green",
    name: "Product Release Procedure",
    status: "Ready for Distribution",
    validUntil: "2025-02-15",
    document: "SOP.0412.01",
    distributionList: "QA Release, Warehouse",
    version: "1.0",
    location: "QA Release Department",
    department: "Quality Assurance",
    reason: "New GMP requirement",
  },
  {
    id: "cc-019",
    documentNumber: "CC-2024-019",
    createdDate: "2024-02-16",
    createdTime: "13:25:45",
    openedBy: "William Davis",
    name: "Complaint Investigation Work Instruction",
    status: "Distributed",
    validUntil: "2025-02-16",
    document: "WI.0145.02",
    distributionList: "Customer Service, QA",
    version: "2.0",
    recipientName: "Complaint Handler",
    distributedDate: "2024-02-17",
    distributedBy: "QA Manager",
    department: "Quality Assurance",
  },
  {
    id: "cc-020",
    documentNumber: "CC-2023-178",
    createdDate: "2023-09-10",
    createdTime: "11:30:20",
    openedBy: "Amanda Lopez",
    name: "Outdated Training Module - GMP Basics",
    status: "Closed - Cancelled",
    validUntil: "2023-12-10",
    document: "TM.0089.01",
    distributionList: "Training Department",
    version: "1.0",
    department: "Training",
    reason: "Replaced by e-learning platform",
  },
  {
    id: "cc-021",
    documentNumber: "CC-2026-021",
    createdDate: "2026-01-20",
    createdTime: "08:30:15",
    openedBy: "Christopher Lee",
    name: "Annual Product Quality Review Template",
    status: "Ready for Distribution",
    validUntil: "2027-01-20",
    document: "TEMP.0234.01",
    distributionList: "QA, Regulatory Affairs",
    version: "1.0",
    location: "QA Review Team",
    department: "Quality Assurance",
    reason: "Annual review cycle",
  },
  {
    id: "cc-022",
    documentNumber: "CC-2026-022",
    createdDate: "2026-01-22",
    createdTime: "10:15:40",
    openedBy: "Patricia Wilson",
    name: "Stability Testing Protocol",
    status: "Distributed",
    validUntil: "2027-01-22",
    document: "PROT.0167.03",
    distributionList: "Stability Lab, R&D",
    version: "3.0",
    recipientName: "Stability Manager",
    distributedDate: "2026-01-23",
    distributedBy: "Lab Director",
    department: "Quality Control",
  },
  {
    id: "cc-023",
    documentNumber: "CC-2026-023",
    createdDate: "2026-01-25",
    createdTime: "14:45:55",
    openedBy: "Charles Martinez",
    name: "Master Batch Record - Product A",
    status: "Ready for Distribution",
    validUntil: "2027-01-25",
    document: "MBR.0456.02",
    distributionList: "Production, Quality Control",
    version: "2.0",
    location: "Production Floor",
    department: "Manufacturing",
    reason: "Process optimization update",
  },
  {
    id: "cc-024",
    documentNumber: "CC-2026-024",
    createdDate: "2026-01-28",
    createdTime: "09:10:30",
    openedBy: "Michelle Taylor",
    name: "Document Control SOP",
    status: "Distributed",
    validUntil: "2027-01-28",
    document: "SOP.0001.05",
    distributionList: "All Departments",
    version: "5.0",
    recipientName: "All Staff",
    distributedDate: "2026-01-29",
    distributedBy: "Document Control Manager",
    department: "Quality Management",
  },
  {
    id: "cc-025",
    documentNumber: "CC-2026-025",
    createdDate: "2026-02-01",
    createdTime: "11:20:45",
    openedBy: "Steven Anderson",
    name: "Water System Maintenance Schedule",
    status: "Ready for Distribution",
    validUntil: "2027-02-01",
    document: "SCH.0089.01",
    distributionList: "Engineering, QA",
    version: "1.0",
    location: "Utilities Department",
    department: "Engineering",
    reason: "Preventive maintenance planning",
  },
  {
    id: "cc-026",
    documentNumber: "CC-2026-026",
    createdDate: "2026-02-03",
    createdTime: "15:35:20",
    openedBy: "Barbara Thompson",
    name: "Vendor Qualification Procedure",
    status: "Distributed",
    validUntil: "2027-02-03",
    document: "SOP.0278.02",
    distributionList: "Procurement, QA",
    version: "2.0",
    recipientName: "Procurement Manager",
    distributedDate: "2026-02-04",
    distributedBy: "QA Director",
    department: "Supply Chain",
  },
  {
    id: "cc-027",
    documentNumber: "CC-2025-234",
    createdDate: "2025-08-15",
    createdTime: "13:50:10",
    openedBy: "Richard Garcia",
    name: "Obsolete Equipment Cleaning Log",
    status: "Obsolete",
    validUntil: "2025-12-15",
    document: "LOG.0156.02",
    distributionList: "Production",
    version: "2.0",
    department: "Manufacturing",
    reason: "Equipment retired from service",
  },
  {
    id: "cc-028",
    documentNumber: "CC-2026-028",
    createdDate: "2026-02-05",
    createdTime: "08:40:35",
    openedBy: "Nancy Rodriguez",
    name: "Risk Assessment Template",
    status: "Ready for Distribution",
    validUntil: "2027-02-05",
    document: "TEMP.0345.01",
    distributionList: "Quality Management, Operations",
    version: "1.0",
    location: "Risk Management Office",
    department: "Quality Management",
    reason: "ISO compliance requirement",
  },
  {
    id: "cc-029",
    documentNumber: "CC-2026-029",
    createdDate: "2026-02-07",
    createdTime: "12:15:50",
    openedBy: "Joseph Hernandez",
    name: "Batch Sampling Procedure",
    status: "Distributed",
    validUntil: "2027-02-07",
    document: "SOP.0389.01",
    distributionList: "Production, QC Lab",
    version: "1.0",
    recipientName: "Lab Technicians",
    distributedDate: "2026-02-08",
    distributedBy: "QC Manager",
    department: "Quality Control",
  },
  {
    id: "cc-030",
    documentNumber: "CC-2024-130",
    createdDate: "2024-06-20",
    createdTime: "10:25:15",
    openedBy: "Linda Moore",
    name: "Cancelled Project Protocol - Phase II",
    status: "Closed - Cancelled",
    validUntil: "2024-09-20",
    document: "PROT.0234.01",
    distributionList: "R&D, Project Team",
    version: "1.0",
    department: "Research & Development",
    reason: "Project discontinued by management",
  },
  {
    id: "cc-031",
    documentNumber: "CC-2026-031",
    createdDate: "2026-02-08",
    createdTime: "14:55:30",
    openedBy: "Mark Jackson",
    name: "Out of Specification Investigation",
    status: "Ready for Distribution",
    validUntil: "2027-02-08",
    document: "SOP.0456.02",
    distributionList: "QC, QA, Production",
    version: "2.0",
    location: "Quality Department",
    department: "Quality Control",
    reason: "Enhanced investigation requirements",
  },
  {
    id: "cc-032",
    documentNumber: "CC-2026-032",
    createdDate: "2026-02-09",
    createdTime: "09:35:45",
    openedBy: "Karen White",
    name: "Internal Audit Checklist - Manufacturing",
    status: "Distributed",
    validUntil: "2026-12-09",
    document: "FORM.0234.01",
    distributionList: "Audit Team",
    version: "1.0",
    recipientName: "Lead Auditor",
    distributedDate: "2026-02-10",
    distributedBy: "QA Manager",
    department: "Quality Assurance",
  },
  {
    id: "cc-033",
    documentNumber: "CC-2026-033",
    createdDate: "2026-02-10",
    createdTime: "11:40:20",
    openedBy: "Brian Clark",
    name: "Analytical Method Validation Protocol",
    status: "Ready for Distribution",
    validUntil: "2027-02-10",
    document: "PROT.0289.01",
    distributionList: "QC Lab, Method Development",
    version: "1.0",
    location: "Analytical Laboratory",
    department: "Quality Control",
    reason: "New analytical method implementation",
  },
  {
    id: "cc-034",
    documentNumber: "CC-2026-034",
    createdDate: "2026-02-11",
    createdTime: "13:20:55",
    openedBy: "Elizabeth Lewis",
    name: "Data Integrity Procedure",
    status: "Distributed",
    validUntil: "2027-02-11",
    document: "SOP.0512.01",
    distributionList: "All Departments",
    version: "1.0",
    recipientName: "All Users",
    distributedDate: "2026-02-11",
    distributedBy: "IT & QA Director",
    department: "IT & Quality",
  },
  {
    id: "cc-035",
    documentNumber: "CC-2025-189",
    createdDate: "2025-07-10",
    createdTime: "15:10:40",
    openedBy: "George Hall",
    name: "Deprecated Equipment Manual - Model X200",
    status: "Obsolete",
    validUntil: "2025-10-10",
    document: "MAN.0167.01",
    distributionList: "Engineering",
    version: "1.0",
    department: "Engineering",
    reason: "Equipment model no longer in use",
  },
];
